# Generated by Django 3.2.6 on 2021-08-17 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('ana_id', models.AutoField(primary_key=True, serialize=False)),
                ('ana_name', models.CharField(max_length=32)),
                ('ana_description', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'analyse',
            },
        ),
        migrations.CreateModel(
            name='BasicRegex',
            fields=[
                ('regex_id', models.AutoField(primary_key=True, serialize=False)),
                ('regex_name', models.CharField(max_length=32)),
                ('regex_context', models.CharField(max_length=256)),
                ('regex_type', models.CharField(max_length=32)),
                ('regex_description', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'basic_regex',
            },
        ),
        migrations.CreateModel(
            name='InnerFunc',
            fields=[
                ('func_id', models.AutoField(primary_key=True, serialize=False)),
                ('func_name', models.CharField(max_length=32)),
                ('func_input', models.CharField(max_length=128)),
                ('func_output', models.CharField(max_length=128)),
                ('func_description', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'inner_func',
            },
        ),
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('rulegroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('rulegroup_name', models.CharField(max_length=32)),
                ('file_features', models.CharField(max_length=128)),
                ('rulegroup_description', models.CharField(max_length=128, null=True)),
                ('analyse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.analyse')),
            ],
            options={
                'db_table': 'rulegroup',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=32)),
                ('rule_description', models.CharField(max_length=128, null=True)),
                ('rule_index', models.IntegerField(null=True)),
                ('rule_exfeatures', models.CharField(max_length=256, null=True)),
                ('rule_infeatures', models.CharField(max_length=256, null=True)),
                ('rule_regex_features', models.CharField(max_length=2048, null=True)),
                ('sourcelog', models.CharField(max_length=4096)),
                ('extract_rule', models.CharField(max_length=4096)),
                ('transform_rule', models.CharField(max_length=512, null=True)),
                ('replace_rule', models.CharField(max_length=512, null=True)),
                ('supply_rule', models.CharField(max_length=512, null=True)),
                ('rulegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.rulegroup')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('field_ename', models.CharField(max_length=32)),
                ('field_cname', models.CharField(max_length=32)),
                ('field_index', models.IntegerField(null=True)),
                ('field_type', models.IntegerField(null=True)),
                ('display_type', models.CharField(default='input', max_length=18)),
                ('is_many', models.IntegerField(default=0)),
                ('is_accurate', models.IntegerField(default=0)),
                ('option', models.CharField(max_length=256, null=True)),
                ('option_type', models.CharField(max_length=256, null=True)),
                ('analyse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.analyse')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.rule')),
                ('rulegroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.rulegroup')),
            ],
            options={
                'db_table': 'fields',
            },
        ),
    ]
