# Generated by Django 3.2.6 on 2021-08-17 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=32)),
                ('pro_status', models.IntegerField(default=0)),
                ('last_status', models.IntegerField(default=0)),
                ('data_path', models.CharField(max_length=1024)),
                ('pro_description', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 34, 25, 334069))),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 34, 25, 334082))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 34, 25, 334090))),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.unit')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='FolderRecords',
            fields=[
                ('folder_id', models.AutoField(primary_key=True, serialize=False)),
                ('folderpath', models.CharField(max_length=128)),
                ('folder_status', models.IntegerField(default=0)),
                ('last_status', models.IntegerField(default=0)),
                ('filecounts', models.IntegerField()),
                ('processed_files', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.project')),
            ],
            options={
                'db_table': 'folder_records',
            },
        ),
        migrations.CreateModel(
            name='FileRecords',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=128)),
                ('file_status', models.IntegerField(default=0)),
                ('last_status', models.IntegerField(default=0, null=True)),
                ('file_encode', models.CharField(max_length=8, null=True)),
                ('data_length', models.IntegerField(default=0, null=True)),
                ('process_length', models.IntegerField(default=0, null=True)),
                ('output_data', models.IntegerField(default=0, null=True)),
                ('folder_records', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.folderrecords')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.rule')),
                ('rulegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.rulegroup')),
            ],
            options={
                'db_table': 'file_records',
            },
        ),
    ]
