# Generated by Django 3.2.6 on 2021-08-18 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 0, 51, 2, 808563)),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 0, 51, 2, 808597)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 0, 51, 2, 808584)),
        ),
    ]
