# Generated by Django 3.2.6 on 2021-08-18 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_auto_20210818_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 6, 50, 27, 598054)),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 6, 50, 27, 598075)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 6, 50, 27, 598067)),
        ),
    ]
