# Generated by Django 3.2.6 on 2021-08-19 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_auto_20210818_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 3, 13, 56, 225159)),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 3, 13, 56, 225179)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 3, 13, 56, 225171)),
        ),
    ]
