# Generated by Django 3.2.6 on 2021-08-17 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('off_id', models.AutoField(primary_key=True, serialize=False)),
                ('offline_name', models.CharField(max_length=32)),
                ('offline_status', models.IntegerField()),
                ('filesize', models.FloatField()),
                ('download_file', models.CharField(max_length=32)),
                ('sdatetime', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 34, 25, 335496))),
                ('edatetime', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 34, 25, 335507))),
            ],
            options={
                'db_table': 'offline',
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark_name', models.CharField(max_length=32)),
                ('mark_type', models.IntegerField()),
                ('mark_qtype', models.CharField(blank=True, max_length=18, null=True)),
                ('is_root', models.IntegerField()),
                ('mark_condations', models.CharField(blank=True, max_length=2048, null=True)),
                ('is_cached', models.IntegerField(default=0)),
                ('cache_name', models.CharField(blank=True, max_length=32, null=True)),
                ('createtime', models.DateTimeField(default=datetime.datetime(2021, 8, 17, 10, 34, 25, 335215))),
                ('mark_pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='queryset.bookmark')),
            ],
            options={
                'db_table': 'bookmark',
            },
        ),
        migrations.CreateModel(
            name='ProjectRuleMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entry.project')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.rule')),
            ],
            options={
                'db_table': 'prm',
                'unique_together': {('project', 'rule')},
            },
        ),
    ]
