# Generated by Django 3.2.6 on 2021-08-18 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 0, 51, 2, 810143)),
        ),
        migrations.AlterField(
            model_name='offline',
            name='edatetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 0, 51, 2, 810514)),
        ),
        migrations.AlterField(
            model_name='offline',
            name='sdatetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 0, 51, 2, 810499)),
        ),
    ]
