# Generated by Django 3.2.6 on 2021-08-19 03:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryset', '0003_auto_20210818_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='createtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 3, 13, 56, 226219)),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='mark_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offline',
            name='edatetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 3, 13, 56, 226503)),
        ),
        migrations.AlterField(
            model_name='offline',
            name='sdatetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 3, 13, 56, 226493)),
        ),
    ]
