rulemapper = {1: {'rules': [{'rule_id': 1,
                             'rule_name': 'eyou_nginx_access_rule',
                             'rule_index': 1,
                             'rule_exfeatures': '',
                             'rule_infeatures': '',
                             'rule_regex_features': '',
                             'extract_rule': '%{IPV4>>req_ip}...\\[%{DATA>>mdate}\\:%{TIME>>time}\\s...\\s\\s%{DATA>>response}\\s...\\s%{DATA>>url}\\s...\\s%{DATA>>to_size}\\s...\\s\\"%{DATA>>useragent}\\"',
                             'transform_rule': "req_ip:$getGeo>>country,city;mdate:$parseDate2('%Y%m%d')>>mdate;url:$getURL>>url",
                             'replace_rule': '',
                             'supply_rule': '',
                             'analyse': {'ana_id': 1, 'ana_name': 'teyou'},
                             'rulegroup': {'rulegroup_id': 1, 'rulegroup_name': 'eyou_nginx_access'},
                             'allfields': ['auth_type',
                                           'city',
                                           'country',
                                           'ctstr',
                                           'del_type',
                                           'dname',
                                           'from_digest',
                                           'from_email',
                                           'mdate',
                                           'module_type',
                                           'req_ip',
                                           'response',
                                           'result',
                                           'source_log',
                                           'subject_digest',
                                           'time',
                                           'to_digest',
                                           'to_size',
                                           'uid',
                                           'umod',
                                           'url',
                                           'useragent',
                                           'username']}]},
              2: {'rules': [{'rule_id': 2,
                             'rule_name': 'eyou_del_mail_rule',
                             'rule_index': 1,
                             'rule_exfeatures': None,
                             'rule_infeatures': None,
                             'rule_regex_features': '.*del_type.*real_acct_name.*from_email.*subject_digest.*sclient_ip.*',
                             'extract_rule': '%{DATE>>mdate}.%{TIME>>time}...del_type..%{DATA>>del_type}\\]...real_acct_name..%{DATA>>username}\\]...from_email..%{DATA>>from_email}\\]..subject_digest..%{DATA>>subject_digest}\\]\\,...client_ip..%{DATA>>req_ip}\\]',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': None,
                             'supply_rule': None,
                             'analyse': {'ana_id': 1, 'ana_name': 'teyou'},
                             'rulegroup': {'rulegroup_id': 2, 'rulegroup_name': 'eyou_del_mail'},
                             'allfields': ['auth_type',
                                           'city',
                                           'country',
                                           'ctstr',
                                           'del_type',
                                           'dname',
                                           'from_digest',
                                           'from_email',
                                           'mdate',
                                           'module_type',
                                           'req_ip',
                                           'response',
                                           'result',
                                           'source_log',
                                           'subject_digest',
                                           'time',
                                           'to_digest',
                                           'to_size',
                                           'uid',
                                           'umod',
                                           'url',
                                           'useragent',
                                           'username']}]},
              3: {'rules': [{'rule_id': 3,
                             'rule_name': 'eyou_deliver_mail_rule',
                             'rule_index': 1,
                             'rule_exfeatures': None,
                             'rule_infeatures': None,
                             'rule_regex_features': '.*to_real_acct_name.*from_digest.*to_digest.*subject_digest.*module_type.*response.*sclient_ip.*',
                             'extract_rule': '%{DATE>>mdate}.%{TIME>>time}...to_real_acct_name..%{DATA>>username}\\]...from_digest..%{DATA>>from_digest}\\]...to_digest..%{DATA>>to_digest}\\]...subject_digest..%{DATA>>subject_digest}\\]...module_type..%{DATA>>model_type}\\]...response..%{DATA>>response}\\]\\sclient_ip..%{IPV4>>req_ip}\\]...',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': None,
                             'supply_rule': None,
                             'analyse': {'ana_id': 1, 'ana_name': 'teyou'},
                             'rulegroup': {'rulegroup_id': 3, 'rulegroup_name': 'eyou_deliver_mail'},
                             'allfields': ['auth_type',
                                           'city',
                                           'country',
                                           'ctstr',
                                           'del_type',
                                           'dname',
                                           'from_digest',
                                           'from_email',
                                           'mdate',
                                           'module_type',
                                           'req_ip',
                                           'response',
                                           'result',
                                           'source_log',
                                           'subject_digest',
                                           'time',
                                           'to_digest',
                                           'to_size',
                                           'uid',
                                           'umod',
                                           'url',
                                           'useragent',
                                           'username']}]},
              4: {'rules': [{'rule_id': 4,
                             'rule_name': 'eyou_auth_rule',
                             'rule_index': 1,
                             'rule_exfeatures': None,
                             'rule_infeatures': None,
                             'rule_regex_features': '.*auth_type.*real_acct_name.*client_ip.*Auth.*',
                             'extract_rule': '%{DATE>>mdate}.%{TIME>>time}...auth_type..%{DATA>>auth_type}\\]...real_acct_name..%{DATA>>username}\\]....client_ip..%{DATA>>req_ip}\\]...Auth.%{AUTHRESULT>>result}',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': None,
                             'supply_rule': None,
                             'analyse': {'ana_id': 1, 'ana_name': 'teyou'},
                             'rulegroup': {'rulegroup_id': 4, 'rulegroup_name': 'eyou_auth'},
                             'allfields': ['auth_type',
                                           'city',
                                           'country',
                                           'ctstr',
                                           'del_type',
                                           'dname',
                                           'from_digest',
                                           'from_email',
                                           'mdate',
                                           'module_type',
                                           'req_ip',
                                           'response',
                                           'result',
                                           'source_log',
                                           'subject_digest',
                                           'time',
                                           'to_digest',
                                           'to_size',
                                           'uid',
                                           'umod',
                                           'url',
                                           'useragent',
                                           'username']}]},
              5: {'rules': [{'rule_id': 5,
                             'rule_name': 'eyou_analystics_rule',
                             'rule_index': 1,
                             'rule_exfeatures': None,
                             'rule_infeatures': None,
                             'rule_regex_features': '.*ip.*ctime.*ctstr.*umod.*uid.*uname.*dname.*',
                             'extract_rule': '%{DATE>>mdate}.%{TIME>>time}...%{IPV4>>req_ip}...ctstr":"%{DATA>>ctstr}"...umod":"%{DATA>>umod}"...uid":"%{DATA>>uid}"...uname":"%{DATA>>userrname}"...dname":"%{DATA>>dname}"...',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': None,
                             'supply_rule': None,
                             'analyse': {'ana_id': 1, 'ana_name': 'teyou'},
                             'rulegroup': {'rulegroup_id': 5, 'rulegroup_name': 'eyou_analystics'},
                             'allfields': ['auth_type',
                                           'city',
                                           'country',
                                           'ctstr',
                                           'del_type',
                                           'dname',
                                           'from_digest',
                                           'from_email',
                                           'mdate',
                                           'module_type',
                                           'req_ip',
                                           'response',
                                           'result',
                                           'source_log',
                                           'subject_digest',
                                           'time',
                                           'to_digest',
                                           'to_size',
                                           'uid',
                                           'umod',
                                           'url',
                                           'useragent',
                                           'username']}]},
              6: {'rules': [{'rule_id': 6,
                             'rule_name': 'coremail_wmsvr_rule',
                             'rule_index': 1,
                             'rule_exfeatures': 'user',
                             'rule_infeatures': 'resultVar',
                             'rule_regex_features': '.*(func=.*remote.*user.*page.*result.*resultVar)*',
                             'extract_rule': '%{TIME>>time}\\s...func=%{DATA>>func},remote=%{IPV4>>req_ip}...=%{DATA>>username},...,result=%{DATA>>result},resultVar=\\[?%{DATA>>result_var}\\]?,(?=opTime|reqTime|resultOthers)...',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': 'result==S_OK>>result=success;result==FS_UNKNOWN>>result=fail',
                             'supply_rule': None,
                             'analyse': {'ana_id': 2, 'ana_name': 'coremail'},
                             'rulegroup': {'rulegroup_id': 6, 'rulegroup_name': 'coremail_wmsvr'},
                             'allfields': ['action_target',
                                           'action_type',
                                           'city',
                                           'country',
                                           'func',
                                           'info',
                                           'mdate',
                                           'req_ip',
                                           'result',
                                           'result_var',
                                           'source_log',
                                           'time',
                                           'to_page',
                                           'username']}]},
              7: {'rules': [{'rule_id': 7,
                             'rule_name': 'coremail_webadmin_rule',
                             'rule_index': 1,
                             'rule_exfeatures': '',
                             'rule_infeatures': 'action.target',
                             'rule_regex_features': '.*(func=.*remote.*uid.*page.*action.type.*action.target,)*',
                             'extract_rule': '%{TIME>>time}\\s...func=%{DATA>>func},remote=%{IPV4>>req_ip}...uid=%{DATA>>username},...,page=%{DATA>>to_page},action.type=%{DATA>>action_type},action.target=%{DATA>>action_target},%{DATA>>result},...',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': 'result==resultOK>>result=success',
                             'supply_rule': None,
                             'analyse': {'ana_id': 2, 'ana_name': 'coremail'},
                             'rulegroup': {'rulegroup_id': 7, 'rulegroup_name': 'coremail_webadmin'},
                             'allfields': ['action_target',
                                           'action_type',
                                           'city',
                                           'country',
                                           'func',
                                           'info',
                                           'mdate',
                                           'req_ip',
                                           'result',
                                           'result_var',
                                           'source_log',
                                           'time',
                                           'to_page',
                                           'username']}]},
              8: {'rules': [{'rule_id': 8,
                             'rule_name': 'coremail_imapsvr_rule',
                             'rule_index': 1,
                             'rule_exfeatures': None,
                             'rule_infeatures': 'success;logout',
                             'rule_regex_features': '.*([logout|success]).*',
                             'extract_rule': '\\(%{TIME>>time}\\)%{DATA>>info}\\sUser\\s%{DATA>>username}(?:\\[.*)?\\sfrom\\s\\[%{DATA>>req_ip}\\]\\s%{ALLDATA>>result}',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': None,
                             'supply_rule': None,
                             'analyse': {'ana_id': 2, 'ana_name': 'coremail'},
                             'rulegroup': {'rulegroup_id': 8, 'rulegroup_name': 'coremail_imapsvr'},
                             'allfields': ['action_target',
                                           'action_type',
                                           'city',
                                           'country',
                                           'func',
                                           'info',
                                           'mdate',
                                           'req_ip',
                                           'result',
                                           'result_var',
                                           'source_log',
                                           'time',
                                           'to_page',
                                           'username']}]},
              9: {'rules': [{'rule_id': 9,
                             'rule_name': 'cromail_pop3svr_rule',
                             'rule_index': 1,
                             'rule_exfeatures': None,
                             'rule_infeatures': 'User',
                             'rule_regex_features': None,
                             'extract_rule': '\\d{1,10}\\s...\\(%{TIME>>time}\\)%{DATA>>info}\\sUser\\s%{DATA>>username}\\sfrom\\s\\[%{IPV4>>req_ip}\\]:...:%{ALLDATA>>retr_msg_mid}',
                             'transform_rule': 'req_ip:$getGeo>>country,city',
                             'replace_rule': None,
                             'supply_rule': None,
                             'analyse': {'ana_id': 2, 'ana_name': 'coremail'},
                             'rulegroup': {'rulegroup_id': 9, 'rulegroup_name': 'coremail_pop3svr'},
                             'allfields': ['action_target',
                                           'action_type',
                                           'city',
                                           'country',
                                           'func',
                                           'info',
                                           'mdate',
                                           'req_ip',
                                           'result',
                                           'result_var',
                                           'source_log',
                                           'time',
                                           'to_page',
                                           'username']}]},
              10: {'rules': [{'rule_id': 10,
                              'rule_name': 'exchange_iis_rule',
                              'rule_index': 1,
                              'rule_exfeatures': None,
                              'rule_infeatures': None,
                              'rule_regex_features': None,
                              'extract_rule': '%{DATE>>mdate}\\s%{TIME>>time}\\s%{IPV4>>server_ip}\\s%{DATA>>req_method}\\s\\/%{DATA>>log_api}\\/...;...;\\s%{DATA>>port}\\s%{DATA>>username}\\s%{IPV4>>req_ip}\\s%{DATA>>user_agent}\\s%{DATA>>url}\\s%{DATA>>response}\\s%{DATA>>status}\\s%{DATA>>params}\\s%{ALLDATA>>to_size}',
                              'transform_rule': 'req_ip:$getGeo>>country,city;url:$getURL>>url',
                              'replace_rule': None,
                              'supply_rule': None,
                              'analyse': {'ana_id': 3, 'ana_name': 'exchange'},
                              'rulegroup': {'rulegroup_id': 10, 'rulegroup_name': 'exchange_iis'},
                              'allfields': ['city',
                                            'country',
                                            'domain',
                                            'log_api',
                                            'log_status',
                                            'mdate',
                                            'params',
                                            'port',
                                            'req_ip',
                                            'req_method',
                                            'response',
                                            'server_ip',
                                            'source_log',
                                            'status',
                                            'time',
                                            'to_size',
                                            'uid',
                                            'url',
                                            'user_agent',
                                            'username']}]},
              11: {'rules': [{'rule_id': 11,
                              'rule_name': 'exchange_ews_rule',
                              'rule_index': 1,
                              'rule_exfeatures': None,
                              'rule_infeatures': 'Ews',
                              'rule_regex_features': None,
                              'extract_rule': '%{DATE>>mdate}T%{TIME>>time}...,...,..,...,...,...,...,...,%{DATA>>domain},...,...,...,...,%{DATA>>username},...,%{DATA>>uid},...,%{DATA>>req_ip},...,%{DATA>>log_status},',
                              'transform_rule': 'req_ip:$getGeo>>country,city',
                              'replace_rule': None,
                              'supply_rule': None,
                              'analyse': {'ana_id': 3, 'ana_name': 'exchange'},
                              'rulegroup': {'rulegroup_id': 11, 'rulegroup_name': 'exchange_ews'},
                              'allfields': ['city',
                                            'country',
                                            'domain',
                                            'log_api',
                                            'log_status',
                                            'mdate',
                                            'params',
                                            'port',
                                            'req_ip',
                                            'req_method',
                                            'response',
                                            'server_ip',
                                            'source_log',
                                            'status',
                                            'time',
                                            'to_size',
                                            'uid',
                                            'url',
                                            'user_agent',
                                            'username']}]},
              12: {'rules': [{'rule_id': 12,
                              'rule_name': 'exchange_owa_rule',
                              'rule_index': 1,
                              'rule_exfeatures': '',
                              'rule_infeatures': 'Owa',
                              'rule_regex_features': None,
                              'extract_rule': '%{DATE>>mdate}T%{TIME>>time}...,...,..,...,...,...,...,...,%{DATA>>domain},...,...,...,...,%{DATA>>username},...,...,...,%{DATA>>req_ip},...,%{DATA>>log_status},',
                              'transform_rule': 'req_ip:$getGeo>>country,city',
                              'replace_rule': None,
                              'supply_rule': None,
                              'analyse': {'ana_id': 3, 'ana_name': 'exchange'},
                              'rulegroup': {'rulegroup_id': 12, 'rulegroup_name': 'exchange_owa'},
                              'allfields': ['city',
                                            'country',
                                            'domain',
                                            'log_api',
                                            'log_status',
                                            'mdate',
                                            'params',
                                            'port',
                                            'req_ip',
                                            'req_method',
                                            'response',
                                            'server_ip',
                                            'source_log',
                                            'status',
                                            'time',
                                            'to_size',
                                            'uid',
                                            'url',
                                            'user_agent',
                                            'username']}]},
              13: {'rules': [{'rule_id': 13,
                              'rule_name': 'exchange_ecp_rule',
                              'rule_index': 1,
                              'rule_exfeatures': '',
                              'rule_infeatures': 'Ecp',
                              'rule_regex_features': None,
                              'extract_rule': '%{DATE>>mdate}T%{TIME>>time}...,...,..,...,...,...,...,...,%{DATA>>domain},...,...,...,...,%{DATA>>username},...,...,...,%{DATA>>req_ip},...,%{DATA>>log_status},',
                              'transform_rule': 'req_ip:$getGeo>>country,city',
                              'replace_rule': None,
                              'supply_rule': None,
                              'analyse': {'ana_id': 3, 'ana_name': 'exchange'},
                              'rulegroup': {'rulegroup_id': 13, 'rulegroup_name': 'exchange_ecp'},
                              'allfields': ['city',
                                            'country',
                                            'domain',
                                            'log_api',
                                            'log_status',
                                            'mdate',
                                            'params',
                                            'port',
                                            'req_ip',
                                            'req_method',
                                            'response',
                                            'server_ip',
                                            'source_log',
                                            'status',
                                            'time',
                                            'to_size',
                                            'uid',
                                            'url',
                                            'user_agent',
                                            'username']}]},
              14: {'rules': [{'rule_id': 14,
                              'rule_name': 'iis_log_rule',
                              'rule_index': 1,
                              'rule_exfeatures': 'fe80;::1',
                              'rule_infeatures': None,
                              'rule_regex_features': '.*-\\s\\w{1,4}\\s\\d{1,15}\\s\\d{1,15}\\s\\d{1,15}\\s(?<![0-9])(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))(?![0-9])',
                              'extract_rule': '%{DATE>>mdate}\\s%{TIME>>time}\\s%{IPV4>>server_ip}\\s%{DATA>>req_method}\\s%{DATA>>to_page}\\s...\\s%{PORT>>port}\\s%{DATA>>username}\\s%{DATA>>req_ip2}\\s%{DATA>>user_agent}\\s...\\s%{PORT>>response}\\s\\d{1,3}\\s%{DATA>>get_size}\\s%{AUSIZE>>send_size}\\s%{IPV4>>req_ip},?%{ALLDATA>>tail_ip}',
                              'transform_rule': 'req_ip:$getGeo>>country,city',
                              'replace_rule': '',
                              'supply_rule': None,
                              'analyse': {'ana_id': 4, 'ana_name': 'iis'},
                              'rulegroup': {'rulegroup_id': 14, 'rulegroup_name': 'iis_log_rg'},
                              'allfields': ['city',
                                            'country',
                                            'get_size',
                                            'mdate',
                                            'port',
                                            'req_ip',
                                            'req_ip2',
                                            'req_method',
                                            'response',
                                            'send_size',
                                            'server_ip',
                                            'sourcelog',
                                            'tail_ip',
                                            'time',
                                            'to_page',
                                            'user_agent',
                                            'username']}]},
              15: {'rules': [{'rule_id': 15,
                              'rule_name': 'iis_txt_rule',
                              'rule_index': 1,
                              'rule_exfeatures': 'fe80;::1',
                              'rule_infeatures': None,
                              'rule_regex_features': '.*-\\s\\w{1,4}\\s\\d{1,15}\\s\\d{1,15}\\s\\d{1,15}\\s(?<![0-9])(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))(?![0-9])',
                              'extract_rule': '%{DATE>>mdate}\\s%{TIME>>time}\\s%{IPV4>>server_ip}\\s%{DATA>>req_method}\\s%{DATA>>to_page}\\s...\\s%{DATA>>port}\\s%{DATA>>username}\\s%{DATA>>req_ip2}\\s%{DATA>>user_agent}\\s...\\s%{DATA>>response}\\s...\\s%{DATA>>get_size}\\s%{DATA>>send_size}\\s%{IPV4>>req_ip},?%{ALLDATA>>tail_ip}',
                              'transform_rule': 'req_ip:$getGeo>>country,city',
                              'replace_rule': '',
                              'supply_rule': None,
                              'analyse': {'ana_id': 4, 'ana_name': 'iis'},
                              'rulegroup': {'rulegroup_id': 15, 'rulegroup_name': 'iis_txt_rg'},
                              'allfields': ['city',
                                            'country',
                                            'get_size',
                                            'mdate',
                                            'port',
                                            'req_ip',
                                            'req_ip2',
                                            'req_method',
                                            'response',
                                            'send_size',
                                            'server_ip',
                                            'sourcelog',
                                            'tail_ip',
                                            'time',
                                            'to_page',
                                            'user_agent',
                                            'username']}]},
              16: {'rules': [{'rule_id': 16,
                              'rule_name': 'iis_csv_rule',
                              'rule_index': 1,
                              'rule_exfeatures': 'fe80;::1',
                              'rule_infeatures': None,
                              'rule_regex_features': '.*-\\s\\w{1,4}\\s\\d{1,15}\\s\\d{1,15}\\s\\d{1,15}\\s(?<![0-9])(?:(?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5])[.](?:[0-1]?[0-9]{1,2}|2[0-4][0-9]|25[0-5]))(?![0-9])',
                              'extract_rule': '%{DATE>>mdate}\\s%{TIME>>time}\\s%{IPV4>>server_ip}\\s%{DATA>>req_method}\\s%{DATA>>to_page}\\s...\\s%{PORT>>port}\\s%{DATA>>username}\\s%{DATA>>req_ip2}\\s%{DATA>>user_agent}\\s...\\s%{PORT>>response}\\s\\d{1,3}\\s%{DATA>>get_size}\\s%{AUSIZE>>send_size}\\s%{IPV4>>req_ip},?%{ALLDATA>>tail_ip}',
                              'transform_rule': 'req_ip:$getGeo>>country,city',
                              'replace_rule': None,
                              'supply_rule': None,
                              'analyse': {'ana_id': 4, 'ana_name': 'iis'},
                              'rulegroup': {'rulegroup_id': 16, 'rulegroup_name': 'iis_csv_rg'},
                              'allfields': ['city',
                                            'country',
                                            'get_size',
                                            'mdate',
                                            'port',
                                            'req_ip',
                                            'req_ip2',
                                            'req_method',
                                            'response',
                                            'send_size',
                                            'server_ip',
                                            'sourcelog',
                                            'tail_ip',
                                            'time',
                                            'to_page',
                                            'user_agent',
                                            'username']}]}}
